[[libheif]]
arch = "aarch64"
git-tree-sha1 = "892f229ae389e8a93ba84e67db55ce81045ec5f2"
os = "macos"

    [[libheif.download]]
    sha256 = "223007aa17e1a9f84e1731df3db429e2d4c34ff35cce9dcc084337fbe5eecea4"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.aarch64-apple-darwin.tar.gz"
[[libheif]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25ca026d57670dabe450c615e9b04d2620faad0a"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "f0b67c6e34c2d1690010da7781e3decdd9006e8a59dc0c09fde8d4b66ac88394"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.aarch64-linux-gnu-cxx03.tar.gz"
[[libheif]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94d9ce623074a0b8e4c06767288c11de6fcbcaaa"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "f259a0f8629db0e757b2018627bb135cb081c2ddc4e1b914ac21ce47b70615ff"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.aarch64-linux-gnu-cxx11.tar.gz"
[[libheif]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "92b01bad105dde264365f9e440dade443c3b7005"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "614bf5fbc6c66337eaaf5e45b03d653f5184015d3721148ef9eaecab89e54a25"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.aarch64-linux-musl-cxx03.tar.gz"
[[libheif]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5f0a1d4d1a334f9200abb3c18059159050b5007"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "4d6023281667f873f3f7cfc3511f666b01ca0314e675a6f3b8b83b5b7a849233"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.aarch64-linux-musl-cxx11.tar.gz"
[[libheif]]
arch = "aarch64"
git-tree-sha1 = "e2d78ce40cb336dea76d1210157eeaf9c11a45bb"
os = "freebsd"

    [[libheif.download]]
    sha256 = "640f791df4577f9662684810382684965e81f6c21f6e68a4168441e5e55fdaf5"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.aarch64-unknown-freebsd.tar.gz"
[[libheif]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "afee1f0f8ab352f59fbf2fa985b3b3ab075e500b"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "edadd56cc5a3296de726485aa098cce940809a328d30f3b4aaabf75a6a8e46b1"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libheif]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef9e8b09eb7949baedc7077c8275a0060aed886f"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "46874601d4ff93179d6c3426fa0ade6dda402635acbf1ecef0bdf50f9cfe6cdc"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libheif]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d819325ff4697b1d365df29fc64571fd7b3b3298"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "f2962b363ce2736fa35fe547d7e6251e3c717a4069a46180ef6de09fdf5feb59"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libheif]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12562a0226e93219f5411ca49c73a4d6adc18df3"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "c216bd1f0f8be9c8eb23c4eecff47b7c982514a4da85c93c29322a732dc5e5ed"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libheif]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8effebc59668f5c9b0a4a6ba64bcaa6a8ebac0a"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "25df97ce6e2bd879e8e2b4733d91e3c40baa25fbc205f30fae0220d9e3e2d639"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libheif]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae31a67fae37740c663f688717f8bf0e15a7171b"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "45e795ed6d0dd67964f2017a7d77b00f935469503e7da1cfa4f00a8388b9fbd3"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libheif]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "55c823f04276ea90e5f6bcded22154869270a6f2"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "e6fd4193b8104e4cfae4859de9ea7f2d54696cfe62c2faa495b20486cdbaf363"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libheif]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "99d6182fcc32578f5f51f4531ae3719912a94d4f"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "1c57268c29b5ad10343d3b2a166b2674d3977f31c3417b366fbc59c725afed33"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libheif]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a60eb3cf85892396edb3ebc349c844128d9e7a4"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "e71b4a6a1f935c489e6215cba8f069e7ed3d000e7a1db55722ae63ecc1579524"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.i686-linux-gnu-cxx03.tar.gz"
[[libheif]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a29638ce53e55e331bf4cb05d28653fc5db83002"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "706bdc9fd802b1bb9c23d8350af30d933c1b1916a98c62181dc76a03df165142"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.i686-linux-gnu-cxx11.tar.gz"
[[libheif]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "318ffbf0da712d983902afaa75d5da917710933f"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "74aa01a8cd62f4c106b49b89630eed81738e7467c446b36319a379b8996d92ec"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.i686-linux-musl-cxx03.tar.gz"
[[libheif]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8198c23008bd27d92b0d9956f6aab3c53891cdbf"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "50ce0fc231a7738767abda4eac87616fd832d799ed6b8801707c3c26a7547d87"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.i686-linux-musl-cxx11.tar.gz"
[[libheif]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d44cb788a17e97c116513c24894e27b9b51ad7d"
os = "windows"

    [[libheif.download]]
    sha256 = "eff14890d1b8435d80645fb135dd23a8deddd228443e02207aee9a62f85e6f6e"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.i686-w64-mingw32-cxx03.tar.gz"
[[libheif]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "596af7a94a73942bc592de0e1393855ddabb16e6"
os = "windows"

    [[libheif.download]]
    sha256 = "6ecb070e946361e8246e86ff129cd94b9cc63aa214c85760f6431aeabe0a097b"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.i686-w64-mingw32-cxx11.tar.gz"
[[libheif]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9371da6f36e3e9290e308e94ccd05f7666b464d7"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "1cb547b54c1406fb1fc6febb3e60e2c430ce01a3fc617278695c257ec56945c1"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libheif]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1cfa83ecb6c822e30dc582b262059b69933d63a"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "42d96fa612d788a287a5b6af0508fa19da808cfc12f4896571789d9690419ec9"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libheif]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee6a00b46c510dac6a69ebc57df8a7b0e42d8959"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "e97902e20cebd655099fdecf0b17e0ecd778d763f867119a605edd2fdae5267c"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.riscv64-linux-gnu-cxx03.tar.gz"
[[libheif]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fa7b97ad280c61764d0e273e829026e859f926d7"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "0c502b3e2f0efbbd5343f51d5f43c5faadc6d486c18ada4133f4d22e0861c491"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.riscv64-linux-gnu-cxx11.tar.gz"
[[libheif]]
arch = "x86_64"
git-tree-sha1 = "400e23239aa9186a0e7c277ca07d98a29082cbcc"
os = "macos"

    [[libheif.download]]
    sha256 = "8388ecd0b6f1711951a4431d4b8f7af06c0e8e98ec563535c59dbf4366c94138"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.x86_64-apple-darwin.tar.gz"
[[libheif]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf667c87c9dc89a202df59ae0844288814a77e28"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "12a345e2a472d8a7684b567943db2265da75644f5699aae65139c4867e0a6b4c"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.x86_64-linux-gnu-cxx03.tar.gz"
[[libheif]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d8754325f84df3a17fbd54d9dfe4b6fe38cc378"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "1d225d86d0a052c0753ae2718ac6d0325e7a55c98bd3ffbcb140c3cdd7b20d3a"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.x86_64-linux-gnu-cxx11.tar.gz"
[[libheif]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b9db38ff795846e99e723e8934326b253674262"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "23d77bb8a7f8e7c99f71a447a2a940b37178451472c260cc529c6f4ad9c7bf05"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.x86_64-linux-musl-cxx03.tar.gz"
[[libheif]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a93ef76aa79030b6901205b854f9b4f7f4cc84c"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "a40c607a686906230df295baf4565cf3c12ef1a3151e4b719326a95ae5d043c2"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.x86_64-linux-musl-cxx11.tar.gz"
[[libheif]]
arch = "x86_64"
git-tree-sha1 = "94400d042f5ed84e1d7dd751696e42ff75561f21"
os = "freebsd"

    [[libheif.download]]
    sha256 = "1a817557c844199d2593c3a962cce9124adf9107a8b48fe72963a6bee4f10fbc"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.x86_64-unknown-freebsd.tar.gz"
[[libheif]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6bf6e70b37a369ef46ce33cfba8f39e1946991db"
os = "windows"

    [[libheif.download]]
    sha256 = "a7efda53832d72f8d5ec594b4c0d38edeabd1c907120c142035f91abc646d3df"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.x86_64-w64-mingw32-cxx03.tar.gz"
[[libheif]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "311066085cf65ad3fddca35bae4ea8353970a146"
os = "windows"

    [[libheif.download]]
    sha256 = "a8cc18a588476469140d659fb3a94f68a69de96ba4920d1e1675d2031424f46c"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.20.1000+0/libheif.v1.20.1000.x86_64-w64-mingw32-cxx11.tar.gz"
