[[libheif]]
arch = "aarch64"
git-tree-sha1 = "083d60ee1bbf5b68ecd0b9fcae664495643a24ef"
os = "macos"

    [[libheif.download]]
    sha256 = "0b0e36d4f48832f8de36c8aa270c73ac9fb41240f15787aeaceeebe7d2a3087c"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.aarch64-apple-darwin.tar.gz"
[[libheif]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca39e5d630d62d16481b93b3e0b1f0cbb9cfff12"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "51811d2d4699c0863cba4ef0e4ca8c55aa1762782e3e2503928ea7e96d20be41"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.aarch64-linux-gnu-cxx11.tar.gz"
[[libheif]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e294c14f9a90586944be31f89f8ca126cd1eaab5"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "6f53fffb766d9d78bb38fc7386053f60dfc665293b087c4fc04ee58fc0a109d1"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.aarch64-linux-musl-cxx11.tar.gz"
[[libheif]]
arch = "aarch64"
git-tree-sha1 = "19ff6797dac7b9ad48f09647b4cfbfdeb4c1678b"
os = "freebsd"

    [[libheif.download]]
    sha256 = "eb44c98cf0f6bf3c29a95756b73fbcfeab9e80947f8d9e8b6a875a2e787c9b62"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.aarch64-unknown-freebsd.tar.gz"
[[libheif]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4c9e168ec3c094828897062e730bfd2e87dfe2b"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "4c2886a85a64c9fccbd3c681cfee101deb928be0ca1fb6287f7f6ea5049cc668"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libheif]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3f25100fae57d32590055063f95a51f4f4f90672"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "0d0973a9c87c18bdb4f2f234e8351a55b755f82945784d264b39432305c19188"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libheif]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c6e21bc1d19ed7ca34327d2487467d9cea72c6d"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "748aac586534b12a5afab9ff85ba0bbc62dda477b67d26678d677de42f0f511a"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libheif]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ccb6f7956187276a74dc5903957013e944c59cbb"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "9f7abb90fa9825e41335fd9f2e180de4f3d35eee685f01237a31c68243552a44"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libheif]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4492b9488d75719bb6ed94d86507829995c77bf5"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "018a3018f39e29da219097465e2d7bf066595de85910ffe78fca4b9b704732ca"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.i686-linux-gnu-cxx11.tar.gz"
[[libheif]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea1a68d6f7c6e7de11ab79b2bcd007f7dee71fad"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "24032f83e8448db2afd8744ca9c0c9901a6964d8550ead0a9ae7266cfc629eb0"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.i686-linux-musl-cxx11.tar.gz"
[[libheif]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "887cc93fb81c538c366228436ea946bb71d05abd"
os = "windows"

    [[libheif.download]]
    sha256 = "f95afb4e9e13231cf486be61e273c6d7872e0f587f8052fec896da2585e2ef73"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.i686-w64-mingw32-cxx11.tar.gz"
[[libheif]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c6b76a2a1c124a6f120460c71bfd45efe3e2cfd"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "4aa550968f99439b29c74a7ecacab92afd8078c4597e04efafecf0e5a3eb2e8d"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libheif]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91762c2304b520a3a459b6cbc3714cbf6c0d99d2"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "cea69b3759107475f5d1de8bfdc040588d881f654a5b7d876bf78e15f6c7a13b"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.riscv64-linux-gnu-cxx11.tar.gz"
[[libheif]]
arch = "x86_64"
git-tree-sha1 = "2c58814604a8c6ba95d7fd993520f0b08f1f78c5"
os = "macos"

    [[libheif.download]]
    sha256 = "ec610284a09b585b89c82deceb8193cb2bc907cce256dc9a00e1d518445c0590"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.x86_64-apple-darwin.tar.gz"
[[libheif]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ce8af90d76ff6b7fc08931900e5ccc25db75f13"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "4551cff4bd3c72e92619b26e999d91b23f2feab07c02f49babd560bb72d35e8a"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.x86_64-linux-gnu-cxx11.tar.gz"
[[libheif]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cb651581144c1a389b9d9a32010d68341a677146"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "b593dac27f74c3dae7b7c7664db1fdbefd5e44f3b5687e0a7034799db777c29f"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.x86_64-linux-musl-cxx11.tar.gz"
[[libheif]]
arch = "x86_64"
git-tree-sha1 = "95b6e3c3e8309d9d311c51a1a4de54cc489f4602"
os = "freebsd"

    [[libheif.download]]
    sha256 = "c643cff0d138c0663442fd922c7b381da1095288bbe08feeaa89bf381e8ee8e2"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.x86_64-unknown-freebsd.tar.gz"
[[libheif]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06aa5653b0a83fe366b16c04c0930777774442ec"
os = "windows"

    [[libheif.download]]
    sha256 = "06efc8283a58180d72dce38bac1a281c8bf7d8d573ad2023d998db01b51542a7"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.23.5000+0/libheif.v1.23.5000.x86_64-w64-mingw32-cxx11.tar.gz"
