[[libheif]]
arch = "aarch64"
git-tree-sha1 = "af3a097fb8d851cde9c27e9f2340035c7fa3231a"
os = "macos"

    [[libheif.download]]
    sha256 = "491427eae4f0f649df30682e077792f9fcd48e8438c90d2db67130d5978404c2"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.aarch64-apple-darwin.tar.gz"
[[libheif]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc5aefbde4de56ece38e67cd6b0686a674862f32"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "1233fd8200131d69373d3b79b790a7342f8b3f21161723f2e16f2e618b8c041f"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.aarch64-linux-gnu-cxx11.tar.gz"
[[libheif]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3542d6137833955d4794c775fa704e52a2f4caee"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "897a715ea8fcbecfc93bec358fe2ed0a4d8b1417d2cc3f1c27adaec313d6d6b0"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.aarch64-linux-musl-cxx11.tar.gz"
[[libheif]]
arch = "aarch64"
git-tree-sha1 = "d52983265f0026977b787621cc13a0e45026e092"
os = "freebsd"

    [[libheif.download]]
    sha256 = "043a7de0aed0359c1437a6ebdb3f0c6bef81a9ddba3f8c23ca934abda1cfcc47"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.aarch64-unknown-freebsd.tar.gz"
[[libheif]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "231450aa4ee3dc652cf2a368a3e1e1684960182d"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "510e326ddb08e71d533523ac9e1dde100ad77cf251a761098e6e56c97690debe"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libheif]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "18626a6e8f8327dcef02913ea0d814813dc1ed80"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "0a1dbc45a04f6e4ab5d8fee88c5300aee18dd546fd8a323ed870c379001a2b00"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libheif]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5293e1a2203218738c0b7fab146b2e8589c6c128"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "a68779146c44b11f32b1c97d38b9cebb11d06bfc6f38d7712cc1c3038b1f790e"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libheif]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ca757ea52719e7873a9dd60f6e08964e76bc980"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "8564551e2f492da772e30b9d7ebabf439137d0af17d28475c2bdcdfbb7ab9b3a"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libheif]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24fe4a7f9badaff22797a7005f585aba03bab807"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "f11edfa40b9927a06e74fe6ebe18f17d909388c9c6ea368b5ca0b087f26b86be"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.i686-linux-gnu-cxx11.tar.gz"
[[libheif]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c422ba74bf2c2a25d2e55e91b44c44dad0ce1093"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "27b3150c974bbb38de7ef684d19f491cbb39cc8473478d37c641f551a5340f84"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.i686-linux-musl-cxx11.tar.gz"
[[libheif]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfabe387b2124a447358f30a070fe485682a4e89"
os = "windows"

    [[libheif.download]]
    sha256 = "9899f252746b4bc524c18437a90f3d101a9b213f75df56b2b689815b5771caa3"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.i686-w64-mingw32-cxx11.tar.gz"
[[libheif]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6ab9a2fea263b0c2d1802b8eaba84b42c8b629b6"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "09824cf3e304f12831c13a3461ee4c66f4c5c7d6273a095dc12acd829a1b166a"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libheif]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c1d99b7bee37295846f5ec41aea4fcadc87ccd16"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "012bdcd22d3ee47e382dcbd64b14df63f42e6f9eaabf455e47e1e99d91d92601"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.riscv64-linux-gnu-cxx11.tar.gz"
[[libheif]]
arch = "x86_64"
git-tree-sha1 = "667078050f7c1702ff4f3a350242a95e57346dd2"
os = "macos"

    [[libheif.download]]
    sha256 = "9e872153e8bae77f402d35a6d0e0bbcf0a68db84b6e96ad1059324f9212196bd"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.x86_64-apple-darwin.tar.gz"
[[libheif]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c9f6d7c0bb9e3e1cfffa0d1c9427cdb9ff934e78"
libc = "glibc"
os = "linux"

    [[libheif.download]]
    sha256 = "ce90fea49ff21e1148ce1e7b9318b711a693dbd154024484d9862718abdf16e2"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.x86_64-linux-gnu-cxx11.tar.gz"
[[libheif]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9525fe10c0300cc0ad297906e432b515f5c48597"
libc = "musl"
os = "linux"

    [[libheif.download]]
    sha256 = "5a95ad184bb400573b7d6446655e1fee7751a63f1e18d2bc7bd7c45ad89d9edd"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.x86_64-linux-musl-cxx11.tar.gz"
[[libheif]]
arch = "x86_64"
git-tree-sha1 = "45a74cb19a2201e0ea79b4da3b399df6a983c4f3"
os = "freebsd"

    [[libheif.download]]
    sha256 = "285d58db71e1a60f667f6700974caca5eded828c743cd3295347f1c9bf6a7559"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.x86_64-unknown-freebsd.tar.gz"
[[libheif]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "401163a2ac7e7efa3d67114ac65ec4406a3ef175"
os = "windows"

    [[libheif.download]]
    sha256 = "d28b54807d7165b8c53a92607f7308e5aea18607327cdecdfd88db032205b6ee"
    url = "https://github.com/JuliaBinaryWrappers/libheif_jll.jl/releases/download/libheif-v1.22.2000+0/libheif.v1.22.2000.x86_64-w64-mingw32-cxx11.tar.gz"
