# Autogenerated wrapper script for libheif_jll for x86_64-apple-darwin
export libheif

using libde265_jll
using libavif_jll
using brotli_jll
using LERC_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("libheif")
JLLWrappers.@declare_library_product(libheif, "@rpath/libheif.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libde265_jll, libavif_jll, brotli_jll, LERC_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        libheif,
        "lib/libheif.1.20.1.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
